spring:
  application:
    name: springcloak

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/gendy
          jwk-set-uri: http://localhost:9090/realms/gendy/protocol/openid-connect/certs

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  auth:
    converter:
      resource-id: gendy-poc
      principal-attribute: preferred_username
